// Code generated by "stringer -type ExportConfig -linecomment"; DO NOT EDIT.

package discovery

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Disabled-0]
	_ = x[Standard-1]
	_ = x[Blackbox-2]
}

const _ExportConfig_name = "disabledstandardblackbox"

var _ExportConfig_index = [...]uint8{0, 8, 16, 24}

func (i ExportConfig) String() string {
	if i < 0 || i >= ExportConfig(len(_ExportConfig_index)-1) {
		return "ExportConfig(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExportConfig_name[_ExportConfig_index[i]:_ExportConfig_index[i+1]]
}
