// Code generated by protoc-gen-go. DO NOT EDIT.
// source: namespace.proto

package discoveryv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Namespace represents a namespace.
type Namespace struct {
	// name is the namespace name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// export configures how the services in namespaces gets exported.
	Export int32 `protobuf:"varint,2,opt,name=export,proto3" json:"export,omitempty"`
	// modified is the the time when the service is created or modified.
	Modified             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=modified,proto3" json:"modified,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecb1e126f615f5dd, []int{0}
}

func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (m *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(m, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Namespace) GetExport() int32 {
	if m != nil {
		return m.Export
	}
	return 0
}

func (m *Namespace) GetModified() *timestamp.Timestamp {
	if m != nil {
		return m.Modified
	}
	return nil
}

func init() {
	proto.RegisterType((*Namespace)(nil), "postfinance.discovery.v1.Namespace")
}

func init() { proto.RegisterFile("namespace.proto", fileDescriptor_ecb1e126f615f5dd) }

var fileDescriptor_ecb1e126f615f5dd = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcf, 0x4b, 0xcc, 0x4d,
	0x2d, 0x2e, 0x48, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x28, 0xc8, 0x2f,
	0x2e, 0x49, 0xcb, 0xcc, 0x4b, 0xcc, 0x4b, 0x4e, 0xd5, 0x4b, 0xc9, 0x2c, 0x4e, 0xce, 0x2f, 0x4b,
	0x2d, 0xaa, 0xd4, 0x2b, 0x33, 0x94, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0xab,
	0x4b, 0x2a, 0x4d, 0xd3, 0x2f, 0xc9, 0xcc, 0x4d, 0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0x80, 0x68, 0x55,
	0xca, 0xe7, 0xe2, 0xf4, 0x83, 0x99, 0x26, 0x24, 0xc4, 0xc5, 0x02, 0x32, 0x5a, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x4b, 0xad, 0x28, 0xc8, 0x2f, 0x2a, 0x91,
	0x60, 0x52, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf2, 0x84, 0xcc, 0xb8, 0x38, 0x72, 0xf3, 0x53, 0x32,
	0xd3, 0x32, 0x53, 0x53, 0x24, 0x98, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0x96, 0xe9,
	0xc1, 0x2c, 0xd3, 0x0b, 0x81, 0x59, 0x16, 0x04, 0x57, 0xeb, 0x64, 0xc3, 0x25, 0x9d, 0x9c, 0xa1,
	0x87, 0xcb, 0xc1, 0x4e, 0x7c, 0x70, 0xd7, 0x04, 0x80, 0x4c, 0x09, 0x60, 0x8c, 0xe2, 0x86, 0xcb,
	0x97, 0x19, 0x26, 0xb1, 0x81, 0xcd, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xbb, 0xc1,
	0xb7, 0x03, 0x01, 0x00, 0x00,
}
