// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service_api.proto

package discoveryv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterServiceRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint             string            `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Labels               map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Description          string            `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Namespace            string            `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RegisterServiceRequest) Reset()         { *m = RegisterServiceRequest{} }
func (m *RegisterServiceRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceRequest) ProtoMessage()    {}
func (*RegisterServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_348f8941aeaf63aa, []int{0}
}

func (m *RegisterServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceRequest.Unmarshal(m, b)
}
func (m *RegisterServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceRequest.Marshal(b, m, deterministic)
}
func (m *RegisterServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceRequest.Merge(m, src)
}
func (m *RegisterServiceRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceRequest.Size(m)
}
func (m *RegisterServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceRequest proto.InternalMessageInfo

func (m *RegisterServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterServiceRequest) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *RegisterServiceRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *RegisterServiceRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RegisterServiceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type RegisterServiceResponse struct {
	Service              *Service `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServiceResponse) Reset()         { *m = RegisterServiceResponse{} }
func (m *RegisterServiceResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterServiceResponse) ProtoMessage()    {}
func (*RegisterServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_348f8941aeaf63aa, []int{1}
}

func (m *RegisterServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServiceResponse.Unmarshal(m, b)
}
func (m *RegisterServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServiceResponse.Marshal(b, m, deterministic)
}
func (m *RegisterServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServiceResponse.Merge(m, src)
}
func (m *RegisterServiceResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterServiceResponse.Size(m)
}
func (m *RegisterServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServiceResponse proto.InternalMessageInfo

func (m *RegisterServiceResponse) GetService() *Service {
	if m != nil {
		return m.Service
	}
	return nil
}

type UnRegisterServiceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegisterServiceRequest) Reset()         { *m = UnRegisterServiceRequest{} }
func (m *UnRegisterServiceRequest) String() string { return proto.CompactTextString(m) }
func (*UnRegisterServiceRequest) ProtoMessage()    {}
func (*UnRegisterServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_348f8941aeaf63aa, []int{2}
}

func (m *UnRegisterServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterServiceRequest.Unmarshal(m, b)
}
func (m *UnRegisterServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterServiceRequest.Marshal(b, m, deterministic)
}
func (m *UnRegisterServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterServiceRequest.Merge(m, src)
}
func (m *UnRegisterServiceRequest) XXX_Size() int {
	return xxx_messageInfo_UnRegisterServiceRequest.Size(m)
}
func (m *UnRegisterServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterServiceRequest proto.InternalMessageInfo

func (m *UnRegisterServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UnRegisterServiceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type UnRegisterServiceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnRegisterServiceResponse) Reset()         { *m = UnRegisterServiceResponse{} }
func (m *UnRegisterServiceResponse) String() string { return proto.CompactTextString(m) }
func (*UnRegisterServiceResponse) ProtoMessage()    {}
func (*UnRegisterServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_348f8941aeaf63aa, []int{3}
}

func (m *UnRegisterServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnRegisterServiceResponse.Unmarshal(m, b)
}
func (m *UnRegisterServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnRegisterServiceResponse.Marshal(b, m, deterministic)
}
func (m *UnRegisterServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnRegisterServiceResponse.Merge(m, src)
}
func (m *UnRegisterServiceResponse) XXX_Size() int {
	return xxx_messageInfo_UnRegisterServiceResponse.Size(m)
}
func (m *UnRegisterServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnRegisterServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnRegisterServiceResponse proto.InternalMessageInfo

type ListServiceRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServiceRequest) Reset()         { *m = ListServiceRequest{} }
func (m *ListServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ListServiceRequest) ProtoMessage()    {}
func (*ListServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_348f8941aeaf63aa, []int{4}
}

func (m *ListServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServiceRequest.Unmarshal(m, b)
}
func (m *ListServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServiceRequest.Marshal(b, m, deterministic)
}
func (m *ListServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServiceRequest.Merge(m, src)
}
func (m *ListServiceRequest) XXX_Size() int {
	return xxx_messageInfo_ListServiceRequest.Size(m)
}
func (m *ListServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServiceRequest proto.InternalMessageInfo

func (m *ListServiceRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type ListServiceResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListServiceResponse) Reset()         { *m = ListServiceResponse{} }
func (m *ListServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ListServiceResponse) ProtoMessage()    {}
func (*ListServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_348f8941aeaf63aa, []int{5}
}

func (m *ListServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServiceResponse.Unmarshal(m, b)
}
func (m *ListServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServiceResponse.Marshal(b, m, deterministic)
}
func (m *ListServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServiceResponse.Merge(m, src)
}
func (m *ListServiceResponse) XXX_Size() int {
	return xxx_messageInfo_ListServiceResponse.Size(m)
}
func (m *ListServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServiceResponse proto.InternalMessageInfo

func (m *ListServiceResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterServiceRequest)(nil), "postfinance.discovery.v1.RegisterServiceRequest")
	proto.RegisterMapType((map[string]string)(nil), "postfinance.discovery.v1.RegisterServiceRequest.LabelsEntry")
	proto.RegisterType((*RegisterServiceResponse)(nil), "postfinance.discovery.v1.RegisterServiceResponse")
	proto.RegisterType((*UnRegisterServiceRequest)(nil), "postfinance.discovery.v1.UnRegisterServiceRequest")
	proto.RegisterType((*UnRegisterServiceResponse)(nil), "postfinance.discovery.v1.UnRegisterServiceResponse")
	proto.RegisterType((*ListServiceRequest)(nil), "postfinance.discovery.v1.ListServiceRequest")
	proto.RegisterType((*ListServiceResponse)(nil), "postfinance.discovery.v1.ListServiceResponse")
}

func init() { proto.RegisterFile("service_api.proto", fileDescriptor_348f8941aeaf63aa) }

var fileDescriptor_348f8941aeaf63aa = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xc7, 0xb5, 0x4e, 0xdb, 0x5f, 0x3b, 0xfe, 0xd1, 0x92, 0xa1, 0xa2, 0xc6, 0x2d, 0x22, 0x58,
	0x42, 0xaa, 0x2a, 0xb0, 0x89, 0x7b, 0x81, 0x42, 0x0f, 0x54, 0x42, 0x02, 0xa9, 0x87, 0x28, 0x14,
	0x0e, 0x5c, 0xd0, 0xd6, 0x5e, 0xc2, 0x8a, 0xb0, 0xbb, 0x78, 0xb7, 0x96, 0xa2, 0xaa, 0x12, 0xe2,
	0x05, 0x38, 0x70, 0xe2, 0xcc, 0xc3, 0xf0, 0x00, 0xbc, 0x02, 0x0f, 0x82, 0xb2, 0xde, 0x84, 0xfc,
	0xa9, 0xa5, 0xe6, 0xe6, 0x9d, 0x9d, 0xef, 0xcc, 0xe7, 0x3b, 0x63, 0x2d, 0x34, 0x35, 0x2b, 0x4a,
	0x9e, 0xb1, 0x77, 0x54, 0xf1, 0x58, 0x15, 0xd2, 0x48, 0x0c, 0x94, 0xd4, 0xe6, 0x3d, 0x17, 0x54,
	0x64, 0x2c, 0xce, 0xb9, 0xce, 0x64, 0xc9, 0x8a, 0x41, 0x5c, 0xb6, 0xc3, 0x6b, 0x2e, 0xb9, 0x4a,
	0x0c, 0x77, 0x7a, 0x52, 0xf6, 0xfa, 0x2c, 0xa1, 0x8a, 0x27, 0x54, 0x08, 0x69, 0xa8, 0xe1, 0x52,
	0xe8, 0xea, 0x36, 0xfa, 0xe1, 0xc1, 0xcd, 0x2e, 0xeb, 0x71, 0x6d, 0x58, 0xf1, 0xaa, 0xd2, 0x75,
	0xd9, 0xe7, 0x33, 0xa6, 0x0d, 0x22, 0x2c, 0x09, 0xfa, 0x89, 0x05, 0xa4, 0x45, 0x76, 0xd7, 0xba,
	0xf6, 0x1b, 0x43, 0x58, 0x65, 0x22, 0x57, 0x92, 0x0b, 0x13, 0x78, 0x36, 0x3e, 0x3e, 0xe3, 0x09,
	0xac, 0xf4, 0xe9, 0x29, 0xeb, 0xeb, 0xa0, 0xd1, 0x6a, 0xec, 0xfa, 0xe9, 0xd3, 0xb8, 0x0e, 0x31,
	0xbe, 0xbc, 0x63, 0x7c, 0x6c, 0xe5, 0xcf, 0x85, 0x29, 0x06, 0x5d, 0x57, 0x0b, 0x5b, 0xe0, 0xe7,
	0x4c, 0x67, 0x05, 0x57, 0x43, 0xec, 0x60, 0xc9, 0x36, 0x9d, 0x0c, 0xe1, 0x0e, 0xac, 0x0d, 0xd9,
	0xb4, 0xa2, 0x19, 0x0b, 0x96, 0xed, 0xfd, 0xbf, 0x40, 0xf8, 0x18, 0xfc, 0x89, 0xb2, 0x78, 0x1d,
	0x1a, 0x1f, 0xd9, 0xc0, 0x79, 0x1a, 0x7e, 0xe2, 0x26, 0x2c, 0x97, 0xb4, 0x7f, 0xc6, 0x9c, 0x9f,
	0xea, 0x70, 0xe0, 0x3d, 0x22, 0xd1, 0x1b, 0xd8, 0x9a, 0x03, 0xd5, 0x4a, 0x0a, 0xcd, 0xf0, 0x09,
	0xfc, 0xe7, 0xa6, 0x6c, 0x4b, 0xf9, 0xe9, 0xdd, 0x7a, 0xb3, 0x23, 0xed, 0x48, 0x11, 0xbd, 0x80,
	0xe0, 0xb5, 0xa8, 0x19, 0xfa, 0x3a, 0x78, 0x3c, 0x77, 0x78, 0x1e, 0xcf, 0xa7, 0xcd, 0x79, 0x33,
	0xe6, 0xa2, 0x6d, 0xb8, 0x75, 0x49, 0xa5, 0x8a, 0x31, 0x4a, 0x01, 0x8f, 0xb9, 0x36, 0x33, 0x0d,
	0xa6, 0x0a, 0x92, 0xd9, 0x82, 0x27, 0x70, 0x63, 0x4a, 0xe3, 0xec, 0x1e, 0xc2, 0xaa, 0x83, 0xd7,
	0x01, 0xb1, 0xcb, 0xbd, 0x82, 0xdf, 0xb1, 0x24, 0xfd, 0xd5, 0x00, 0x70, 0xd1, 0x67, 0x9d, 0x97,
	0xf8, 0x8d, 0xc0, 0xc6, 0x0c, 0x34, 0x3e, 0x5c, 0xf4, 0x67, 0x09, 0xdb, 0x0b, 0x28, 0xdc, 0x44,
	0xb6, 0xbe, 0xfe, 0xfe, 0xf3, 0xdd, 0x6b, 0x46, 0xff, 0x27, 0x65, 0x3b, 0x19, 0xd1, 0x1d, 0x90,
	0x3d, 0xfc, 0x49, 0xa0, 0x39, 0x37, 0x48, 0x4c, 0xeb, 0x3b, 0xd4, 0xed, 0x2f, 0xdc, 0x5f, 0x48,
	0xe3, 0xb8, 0xee, 0x59, 0xae, 0x3b, 0x7b, 0xb7, 0x27, 0xb9, 0x92, 0xf3, 0xf1, 0x5a, 0x2e, 0x92,
	0x73, 0x9e, 0x5f, 0xe0, 0x17, 0x02, 0xfe, 0xc4, 0x76, 0xf0, 0x7e, 0x7d, 0xaf, 0xf9, 0xc5, 0x87,
	0x0f, 0xae, 0x98, 0xed, 0x98, 0x36, 0x2d, 0xd3, 0x3a, 0x4e, 0xcd, 0xea, 0xe8, 0x10, 0xb6, 0xb3,
	0x0f, 0xb5, 0x85, 0x8e, 0x36, 0x46, 0x5b, 0x56, 0xbc, 0x33, 0x7c, 0x5e, 0x3a, 0xe4, 0xad, 0x3f,
	0x4e, 0x28, 0xdb, 0xa7, 0x2b, 0xf6, 0xd1, 0xd9, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xdc,
	0x76, 0x78, 0xd0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServiceAPIClient is the client API for ServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceAPIClient interface {
	// RegisterService registers a service.
	RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error)
	// UnRegisterService unregisters a service.
	UnRegisterService(ctx context.Context, in *UnRegisterServiceRequest, opts ...grpc.CallOption) (*UnRegisterServiceResponse, error)
	// ListService lists all services.
	ListService(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (*ListServiceResponse, error)
}

type serviceAPIClient struct {
	cc *grpc.ClientConn
}

func NewServiceAPIClient(cc *grpc.ClientConn) ServiceAPIClient {
	return &serviceAPIClient{cc}
}

func (c *serviceAPIClient) RegisterService(ctx context.Context, in *RegisterServiceRequest, opts ...grpc.CallOption) (*RegisterServiceResponse, error) {
	out := new(RegisterServiceResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.ServiceAPI/RegisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAPIClient) UnRegisterService(ctx context.Context, in *UnRegisterServiceRequest, opts ...grpc.CallOption) (*UnRegisterServiceResponse, error) {
	out := new(UnRegisterServiceResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.ServiceAPI/UnRegisterService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAPIClient) ListService(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (*ListServiceResponse, error) {
	out := new(ListServiceResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.ServiceAPI/ListService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAPIServer is the server API for ServiceAPI service.
type ServiceAPIServer interface {
	// RegisterService registers a service.
	RegisterService(context.Context, *RegisterServiceRequest) (*RegisterServiceResponse, error)
	// UnRegisterService unregisters a service.
	UnRegisterService(context.Context, *UnRegisterServiceRequest) (*UnRegisterServiceResponse, error)
	// ListService lists all services.
	ListService(context.Context, *ListServiceRequest) (*ListServiceResponse, error)
}

// UnimplementedServiceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedServiceAPIServer struct {
}

func (*UnimplementedServiceAPIServer) RegisterService(ctx context.Context, req *RegisterServiceRequest) (*RegisterServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterService not implemented")
}
func (*UnimplementedServiceAPIServer) UnRegisterService(ctx context.Context, req *UnRegisterServiceRequest) (*UnRegisterServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnRegisterService not implemented")
}
func (*UnimplementedServiceAPIServer) ListService(ctx context.Context, req *ListServiceRequest) (*ListServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListService not implemented")
}

func RegisterServiceAPIServer(s *grpc.Server, srv ServiceAPIServer) {
	s.RegisterService(&_ServiceAPI_serviceDesc, srv)
}

func _ServiceAPI_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.ServiceAPI/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).RegisterService(ctx, req.(*RegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAPI_UnRegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnRegisterServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).UnRegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.ServiceAPI/UnRegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).UnRegisterService(ctx, req.(*UnRegisterServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAPI_ListService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAPIServer).ListService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.ServiceAPI/ListService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAPIServer).ListService(ctx, req.(*ListServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postfinance.discovery.v1.ServiceAPI",
	HandlerType: (*ServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterService",
			Handler:    _ServiceAPI_RegisterService_Handler,
		},
		{
			MethodName: "UnRegisterService",
			Handler:    _ServiceAPI_UnRegisterService_Handler,
		},
		{
			MethodName: "ListService",
			Handler:    _ServiceAPI_ListService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_api.proto",
}
