// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server_api.proto

package discoveryv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// you can disable and enable a server by setting status field.
type RegisterServerRequest_Status int32

const (
	RegisterServerRequest_Undefined RegisterServerRequest_Status = 0
	RegisterServerRequest_Enabled   RegisterServerRequest_Status = 1
	RegisterServerRequest_Disabled  RegisterServerRequest_Status = 2
)

var RegisterServerRequest_Status_name = map[int32]string{
	0: "Undefined",
	1: "Enabled",
	2: "Disabled",
}

var RegisterServerRequest_Status_value = map[string]int32{
	"Undefined": 0,
	"Enabled":   1,
	"Disabled":  2,
}

func (x RegisterServerRequest_Status) String() string {
	return proto.EnumName(RegisterServerRequest_Status_name, int32(x))
}

func (RegisterServerRequest_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{0, 0}
}

type RegisterServerRequest struct {
	Name                 string                       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels               map[string]string            `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status               RegisterServerRequest_Status `protobuf:"varint,3,opt,name=status,proto3,enum=postfinance.discovery.v1.RegisterServerRequest_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *RegisterServerRequest) Reset()         { *m = RegisterServerRequest{} }
func (m *RegisterServerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServerRequest) ProtoMessage()    {}
func (*RegisterServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{0}
}

func (m *RegisterServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServerRequest.Unmarshal(m, b)
}
func (m *RegisterServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServerRequest.Merge(m, src)
}
func (m *RegisterServerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterServerRequest.Size(m)
}
func (m *RegisterServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServerRequest proto.InternalMessageInfo

func (m *RegisterServerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterServerRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *RegisterServerRequest) GetStatus() RegisterServerRequest_Status {
	if m != nil {
		return m.Status
	}
	return RegisterServerRequest_Undefined
}

type RegisterServerResponse struct {
	Server               *Server  `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterServerResponse) Reset()         { *m = RegisterServerResponse{} }
func (m *RegisterServerResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterServerResponse) ProtoMessage()    {}
func (*RegisterServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{1}
}

func (m *RegisterServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterServerResponse.Unmarshal(m, b)
}
func (m *RegisterServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterServerResponse.Marshal(b, m, deterministic)
}
func (m *RegisterServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterServerResponse.Merge(m, src)
}
func (m *RegisterServerResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterServerResponse.Size(m)
}
func (m *RegisterServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterServerResponse proto.InternalMessageInfo

func (m *RegisterServerResponse) GetServer() *Server {
	if m != nil {
		return m.Server
	}
	return nil
}

type UnregisterServerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterServerRequest) Reset()         { *m = UnregisterServerRequest{} }
func (m *UnregisterServerRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterServerRequest) ProtoMessage()    {}
func (*UnregisterServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{2}
}

func (m *UnregisterServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterServerRequest.Unmarshal(m, b)
}
func (m *UnregisterServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterServerRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterServerRequest.Merge(m, src)
}
func (m *UnregisterServerRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterServerRequest.Size(m)
}
func (m *UnregisterServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterServerRequest proto.InternalMessageInfo

func (m *UnregisterServerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UnregisterServerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterServerResponse) Reset()         { *m = UnregisterServerResponse{} }
func (m *UnregisterServerResponse) String() string { return proto.CompactTextString(m) }
func (*UnregisterServerResponse) ProtoMessage()    {}
func (*UnregisterServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{3}
}

func (m *UnregisterServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterServerResponse.Unmarshal(m, b)
}
func (m *UnregisterServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterServerResponse.Marshal(b, m, deterministic)
}
func (m *UnregisterServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterServerResponse.Merge(m, src)
}
func (m *UnregisterServerResponse) XXX_Size() int {
	return xxx_messageInfo_UnregisterServerResponse.Size(m)
}
func (m *UnregisterServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterServerResponse proto.InternalMessageInfo

type ListServerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListServerRequest) Reset()         { *m = ListServerRequest{} }
func (m *ListServerRequest) String() string { return proto.CompactTextString(m) }
func (*ListServerRequest) ProtoMessage()    {}
func (*ListServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{4}
}

func (m *ListServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServerRequest.Unmarshal(m, b)
}
func (m *ListServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServerRequest.Marshal(b, m, deterministic)
}
func (m *ListServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServerRequest.Merge(m, src)
}
func (m *ListServerRequest) XXX_Size() int {
	return xxx_messageInfo_ListServerRequest.Size(m)
}
func (m *ListServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListServerRequest proto.InternalMessageInfo

type ListServerResponse struct {
	Servers              []*Server `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListServerResponse) Reset()         { *m = ListServerResponse{} }
func (m *ListServerResponse) String() string { return proto.CompactTextString(m) }
func (*ListServerResponse) ProtoMessage()    {}
func (*ListServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6011012888d6542c, []int{5}
}

func (m *ListServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListServerResponse.Unmarshal(m, b)
}
func (m *ListServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListServerResponse.Marshal(b, m, deterministic)
}
func (m *ListServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListServerResponse.Merge(m, src)
}
func (m *ListServerResponse) XXX_Size() int {
	return xxx_messageInfo_ListServerResponse.Size(m)
}
func (m *ListServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListServerResponse proto.InternalMessageInfo

func (m *ListServerResponse) GetServers() []*Server {
	if m != nil {
		return m.Servers
	}
	return nil
}

func init() {
	proto.RegisterEnum("postfinance.discovery.v1.RegisterServerRequest_Status", RegisterServerRequest_Status_name, RegisterServerRequest_Status_value)
	proto.RegisterType((*RegisterServerRequest)(nil), "postfinance.discovery.v1.RegisterServerRequest")
	proto.RegisterMapType((map[string]string)(nil), "postfinance.discovery.v1.RegisterServerRequest.LabelsEntry")
	proto.RegisterType((*RegisterServerResponse)(nil), "postfinance.discovery.v1.RegisterServerResponse")
	proto.RegisterType((*UnregisterServerRequest)(nil), "postfinance.discovery.v1.UnregisterServerRequest")
	proto.RegisterType((*UnregisterServerResponse)(nil), "postfinance.discovery.v1.UnregisterServerResponse")
	proto.RegisterType((*ListServerRequest)(nil), "postfinance.discovery.v1.ListServerRequest")
	proto.RegisterType((*ListServerResponse)(nil), "postfinance.discovery.v1.ListServerResponse")
}

func init() { proto.RegisterFile("server_api.proto", fileDescriptor_6011012888d6542c) }

var fileDescriptor_6011012888d6542c = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x7d, 0xe3, 0x3c, 0x5c, 0x72, 0xdd, 0x46, 0xe6, 0x52, 0x8a, 0x65, 0x58, 0x44, 0x5e, 0x45,
	0x05, 0x6c, 0x62, 0x24, 0x54, 0x02, 0x1b, 0x2a, 0xba, 0x40, 0xaa, 0x50, 0xe4, 0xa8, 0x1b, 0x36,
	0x68, 0x92, 0x4c, 0xc3, 0x08, 0x33, 0x36, 0x9e, 0x89, 0xa5, 0x08, 0xd8, 0xb0, 0x65, 0x89, 0xf8,
	0x0e, 0x3e, 0x81, 0x8f, 0xe0, 0x17, 0xf8, 0x10, 0x94, 0x99, 0x29, 0xa4, 0x2d, 0x16, 0xc9, 0xce,
	0x73, 0xe7, 0x9c, 0x73, 0xcf, 0xbd, 0xc7, 0x1a, 0xf0, 0x25, 0xab, 0x6a, 0x56, 0xbd, 0xa2, 0x25,
	0x8f, 0xcb, 0xaa, 0x50, 0x05, 0x06, 0x65, 0x21, 0xd5, 0x29, 0x17, 0x54, 0x4c, 0x58, 0x3c, 0xe5,
	0x72, 0x52, 0xd4, 0xac, 0x5a, 0xc4, 0x75, 0x3f, 0xdc, 0x36, 0x58, 0x83, 0x0b, 0x6f, 0xcf, 0x8a,
	0x62, 0x96, 0xb3, 0x84, 0x96, 0x3c, 0xa1, 0x42, 0x14, 0x8a, 0x2a, 0x5e, 0x08, 0x69, 0x6e, 0xa3,
	0xef, 0x0e, 0xdc, 0xc8, 0xd8, 0x8c, 0x4b, 0xc5, 0xaa, 0x91, 0xa6, 0x65, 0xec, 0xdd, 0x9c, 0x49,
	0x85, 0x08, 0xff, 0x0b, 0xfa, 0x96, 0x05, 0xa4, 0x4b, 0x7a, 0xed, 0x4c, 0x7f, 0xe3, 0x08, 0xdc,
	0x9c, 0x8e, 0x59, 0x2e, 0x03, 0xa7, 0xdb, 0xea, 0x79, 0xe9, 0xe3, 0xb8, 0xc9, 0x44, 0xfc, 0x57,
	0xd1, 0xf8, 0x58, 0xb3, 0x8f, 0x84, 0xaa, 0x16, 0x99, 0x95, 0xc2, 0x17, 0xe0, 0x4a, 0x45, 0xd5,
	0x5c, 0x06, 0xad, 0x2e, 0xe9, 0x75, 0xd2, 0x87, 0x9b, 0x8a, 0x8e, 0x34, 0x3b, 0xb3, 0x2a, 0xe1,
	0x23, 0xf0, 0x56, 0xda, 0xa0, 0x0f, 0xad, 0x37, 0x6c, 0x61, 0xc7, 0x58, 0x7e, 0xe2, 0x2e, 0x5c,
	0xa9, 0x69, 0x3e, 0x67, 0x81, 0xa3, 0x6b, 0xe6, 0x30, 0x70, 0x0e, 0x48, 0x94, 0x82, 0x6b, 0xc4,
	0x70, 0x07, 0xda, 0x27, 0x62, 0xca, 0x4e, 0xb9, 0x60, 0x53, 0xff, 0x3f, 0xf4, 0x60, 0xeb, 0x48,
	0xd0, 0x71, 0xce, 0xa6, 0x3e, 0xc1, 0x6d, 0xb8, 0xfa, 0x8c, 0x4b, 0x73, 0x72, 0xa2, 0x0c, 0xf6,
	0x2e, 0xda, 0x92, 0x65, 0x21, 0x24, 0xc3, 0x03, 0x70, 0x4d, 0x12, 0xba, 0xb9, 0x97, 0x76, 0x9b,
	0x07, 0xb3, 0x4c, 0x8b, 0x8f, 0xee, 0xc1, 0xcd, 0x13, 0x51, 0xad, 0x1b, 0x4b, 0x14, 0x42, 0x70,
	0x19, 0x6e, 0x4c, 0x44, 0xd7, 0xe1, 0xda, 0x31, 0x97, 0xea, 0x9c, 0x48, 0x34, 0x04, 0x5c, 0x2d,
	0x5a, 0xbf, 0x03, 0xd8, 0x32, 0xfd, 0x65, 0x40, 0x74, 0xbc, 0xff, 0x36, 0x7c, 0x46, 0x48, 0xbf,
	0xb5, 0xa0, 0x6d, 0x6a, 0x4f, 0x87, 0xcf, 0xf1, 0x33, 0x81, 0xce, 0xf9, 0xa5, 0x60, 0xb2, 0x61,
	0xaa, 0xe1, 0xfd, 0xf5, 0x09, 0x76, 0xd4, 0xbd, 0x4f, 0x3f, 0x7e, 0x7e, 0x71, 0xfc, 0xc8, 0x4b,
	0xea, 0x7e, 0x62, 0x8d, 0x0d, 0xc8, 0x3e, 0x7e, 0x25, 0xe0, 0x5f, 0xdc, 0x0f, 0xf6, 0x9b, 0xe5,
	0x1b, 0x56, 0x1f, 0xa6, 0x9b, 0x50, 0xac, 0xa7, 0x50, 0x7b, 0xda, 0xdd, 0xc7, 0x15, 0x4f, 0xc9,
	0xfb, 0x65, 0x6a, 0x1f, 0xf1, 0x03, 0xc0, 0x9f, 0x14, 0xf0, 0x4e, 0xb3, 0xfa, 0xa5, 0x00, 0xc3,
	0xbb, 0xeb, 0x81, 0xcf, 0xfe, 0x01, 0x6d, 0x62, 0x07, 0x57, 0x17, 0x73, 0xf8, 0x04, 0x6e, 0x4d,
	0x5e, 0x37, 0xca, 0x1c, 0x76, 0x6c, 0x9a, 0x25, 0x1f, 0x2e, 0x1f, 0x8a, 0x21, 0x79, 0xe9, 0xfd,
	0xbe, 0xaf, 0xfb, 0x63, 0x57, 0x3f, 0x1f, 0x0f, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x2c,
	0xb0, 0x64, 0x98, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerAPIClient is the client API for ServerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerAPIClient interface {
	// RegisterServer registers a server.
	RegisterServer(ctx context.Context, in *RegisterServerRequest, opts ...grpc.CallOption) (*RegisterServerResponse, error)
	// UnRegisterServer unregisters a server.
	UnregisterServer(ctx context.Context, in *UnregisterServerRequest, opts ...grpc.CallOption) (*UnregisterServerResponse, error)
	// ListServer lists all servers.
	ListServer(ctx context.Context, in *ListServerRequest, opts ...grpc.CallOption) (*ListServerResponse, error)
}

type serverAPIClient struct {
	cc *grpc.ClientConn
}

func NewServerAPIClient(cc *grpc.ClientConn) ServerAPIClient {
	return &serverAPIClient{cc}
}

func (c *serverAPIClient) RegisterServer(ctx context.Context, in *RegisterServerRequest, opts ...grpc.CallOption) (*RegisterServerResponse, error) {
	out := new(RegisterServerResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.ServerAPI/RegisterServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverAPIClient) UnregisterServer(ctx context.Context, in *UnregisterServerRequest, opts ...grpc.CallOption) (*UnregisterServerResponse, error) {
	out := new(UnregisterServerResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.ServerAPI/UnregisterServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverAPIClient) ListServer(ctx context.Context, in *ListServerRequest, opts ...grpc.CallOption) (*ListServerResponse, error) {
	out := new(ListServerResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.ServerAPI/ListServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerAPIServer is the server API for ServerAPI service.
type ServerAPIServer interface {
	// RegisterServer registers a server.
	RegisterServer(context.Context, *RegisterServerRequest) (*RegisterServerResponse, error)
	// UnRegisterServer unregisters a server.
	UnregisterServer(context.Context, *UnregisterServerRequest) (*UnregisterServerResponse, error)
	// ListServer lists all servers.
	ListServer(context.Context, *ListServerRequest) (*ListServerResponse, error)
}

// UnimplementedServerAPIServer can be embedded to have forward compatible implementations.
type UnimplementedServerAPIServer struct {
}

func (*UnimplementedServerAPIServer) RegisterServer(ctx context.Context, req *RegisterServerRequest) (*RegisterServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServer not implemented")
}
func (*UnimplementedServerAPIServer) UnregisterServer(ctx context.Context, req *UnregisterServerRequest) (*UnregisterServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterServer not implemented")
}
func (*UnimplementedServerAPIServer) ListServer(ctx context.Context, req *ListServerRequest) (*ListServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServer not implemented")
}

func RegisterServerAPIServer(s *grpc.Server, srv ServerAPIServer) {
	s.RegisterService(&_ServerAPI_serviceDesc, srv)
}

func _ServerAPI_RegisterServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerAPIServer).RegisterServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.ServerAPI/RegisterServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerAPIServer).RegisterServer(ctx, req.(*RegisterServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerAPI_UnregisterServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerAPIServer).UnregisterServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.ServerAPI/UnregisterServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerAPIServer).UnregisterServer(ctx, req.(*UnregisterServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerAPI_ListServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerAPIServer).ListServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.ServerAPI/ListServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerAPIServer).ListServer(ctx, req.(*ListServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postfinance.discovery.v1.ServerAPI",
	HandlerType: (*ServerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterServer",
			Handler:    _ServerAPI_RegisterServer_Handler,
		},
		{
			MethodName: "UnregisterServer",
			Handler:    _ServerAPI_UnregisterServer_Handler,
		},
		{
			MethodName: "ListServer",
			Handler:    _ServerAPI_ListServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_api.proto",
}
