// Code generated by protoc-gen-go. DO NOT EDIT.
// source: token_api.proto

package discoveryv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	// id is an id to identify the token.
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespaces           []string `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Expires              string   `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3b658d759567d3, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateRequest) GetNamespaces() []string {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *CreateRequest) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

type CreateResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3b658d759567d3, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3b658d759567d3, []int{2}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InfoResponse struct {
	Tokeninfo            *TokenInfo `protobuf:"bytes,1,opt,name=tokeninfo,proto3" json:"tokeninfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd3b658d759567d3, []int{3}
}

func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetTokeninfo() *TokenInfo {
	if m != nil {
		return m.Tokeninfo
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "postfinance.discovery.v1.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "postfinance.discovery.v1.CreateResponse")
	proto.RegisterType((*InfoRequest)(nil), "postfinance.discovery.v1.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "postfinance.discovery.v1.InfoResponse")
}

func init() { proto.RegisterFile("token_api.proto", fileDescriptor_dd3b658d759567d3) }

var fileDescriptor_dd3b658d759567d3 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0xd3, 0xf2, 0xff, 0xa3, 0x0c, 0x02, 0xc9, 0x06, 0x93, 0xa6, 0x1a, 0x43, 0x4a, 0x44,
	0xe2, 0xa1, 0x0d, 0x78, 0xd3, 0x13, 0x78, 0xe2, 0x86, 0xc4, 0x8b, 0x5e, 0xcc, 0x5a, 0x06, 0xdc,
	0xa8, 0xbb, 0x4b, 0x77, 0x6d, 0x34, 0xc6, 0x8b, 0xaf, 0xe0, 0xa3, 0xf9, 0x0a, 0xbe, 0x80, 0x6f,
	0x60, 0xd8, 0xa5, 0x80, 0x89, 0x0d, 0xa7, 0x66, 0x3a, 0xbf, 0xf9, 0xe6, 0xdb, 0x2f, 0x03, 0x35,
	0x2d, 0xee, 0x91, 0xdf, 0x50, 0xc9, 0x42, 0x99, 0x08, 0x2d, 0x88, 0x27, 0x85, 0xd2, 0x13, 0xc6,
	0x29, 0x8f, 0x31, 0x1c, 0x33, 0x15, 0x8b, 0x14, 0x93, 0x97, 0x30, 0xed, 0xf8, 0x16, 0x65, 0x7c,
	0x22, 0x2c, 0xea, 0xef, 0x4f, 0x85, 0x98, 0x3e, 0x60, 0x44, 0x25, 0x8b, 0x28, 0xe7, 0x42, 0x53,
	0xcd, 0x04, 0x57, 0xb6, 0x1b, 0x5c, 0x41, 0xe5, 0x3c, 0x41, 0xaa, 0x71, 0x84, 0xb3, 0x27, 0x54,
	0x9a, 0x54, 0xc1, 0x65, 0x63, 0xcf, 0x69, 0x38, 0xed, 0xd2, 0xc8, 0x65, 0x63, 0x72, 0x00, 0xc0,
	0xe9, 0x23, 0x2a, 0x49, 0x63, 0x54, 0x9e, 0xdb, 0x28, 0xb4, 0x4b, 0xa3, 0xb5, 0x3f, 0xc4, 0x83,
	0x2d, 0x7c, 0x96, 0x2c, 0x41, 0xe5, 0x15, 0xcc, 0x50, 0x56, 0x06, 0x2d, 0xa8, 0x66, 0xd2, 0x4a,
	0x0a, 0xae, 0x90, 0xd4, 0xe1, 0xbf, 0x71, 0xb7, 0x90, 0xb7, 0x45, 0xd0, 0x84, 0xf2, 0x80, 0x4f,
	0x44, 0x66, 0xe0, 0x6f, 0xe8, 0x02, 0x76, 0x2c, 0xb4, 0x90, 0xea, 0x41, 0x69, 0xf9, 0x50, 0x43,
	0x96, 0xbb, 0xcd, 0x30, 0x2f, 0x94, 0xf0, 0x72, 0x8e, 0x9a, 0xf9, 0xd5, 0x54, 0xf7, 0xdb, 0x81,
	0x6d, 0xd3, 0xe8, 0x0d, 0x07, 0x24, 0x81, 0xa2, 0x35, 0x4b, 0x8e, 0xf2, 0x65, 0x7e, 0x25, 0xe5,
	0xb7, 0x37, 0x83, 0xd6, 0x6c, 0xb0, 0xfb, 0xfe, 0xf9, 0xf5, 0xe1, 0xd6, 0x02, 0x88, 0xd2, 0x4e,
	0x64, 0x0c, 0xa8, 0x53, 0xe7, 0x98, 0xcc, 0xe0, 0xdf, 0xdc, 0x13, 0x39, 0xcc, 0x17, 0x5a, 0x0b,
	0xc6, 0x6f, 0x6d, 0xc2, 0x16, 0xdb, 0x7c, 0xb3, 0xad, 0x4e, 0xc8, 0x6a, 0x5b, 0xf4, 0x6a, 0xbe,
	0x6f, 0xfd, 0x33, 0xd8, 0x8b, 0xef, 0x72, 0x75, 0xfa, 0x15, 0x9b, 0x87, 0x64, 0xc3, 0xf9, 0x71,
	0x0c, 0x9d, 0xeb, 0xf2, 0xb2, 0x9d, 0x76, 0x6e, 0x8b, 0xe6, 0x64, 0x4e, 0x7e, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xba, 0xd7, 0xd3, 0xee, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TokenAPIClient is the client API for TokenAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TokenAPIClient interface {
	// Create creates a token.
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// Info gives token information.
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type tokenAPIClient struct {
	cc *grpc.ClientConn
}

func NewTokenAPIClient(cc *grpc.ClientConn) TokenAPIClient {
	return &tokenAPIClient{cc}
}

func (c *tokenAPIClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.TokenAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenAPIClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/postfinance.discovery.v1.TokenAPI/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenAPIServer is the server API for TokenAPI service.
type TokenAPIServer interface {
	// Create creates a token.
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// Info gives token information.
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

// UnimplementedTokenAPIServer can be embedded to have forward compatible implementations.
type UnimplementedTokenAPIServer struct {
}

func (*UnimplementedTokenAPIServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTokenAPIServer) Info(ctx context.Context, req *InfoRequest) (*InfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}

func RegisterTokenAPIServer(s *grpc.Server, srv TokenAPIServer) {
	s.RegisterService(&_TokenAPI_serviceDesc, srv)
}

func _TokenAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.TokenAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenAPIServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenAPI_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenAPIServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postfinance.discovery.v1.TokenAPI/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenAPIServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postfinance.discovery.v1.TokenAPI",
	HandlerType: (*TokenAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TokenAPI_Create_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _TokenAPI_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token_api.proto",
}
